version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresmoneo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: moneoApi            # cria o DB “teste” automaticamente
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  moneo-api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: moneo-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"   # API
      - "5005:5005"   # debug remoto
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/moneoApi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
